const products = [
  {
    brand: 'Ford',
    model: 'Focus',
    year: '2020',
    name: 'Premium Car Cover',
    description: 'Protective car cover for all weather conditions.',
    price: 89.99,
  },
  {
    brand: 'Renault',
    model: 'Clio',
    year: '2021',
    name: 'Roof Rack',
    description: 'Sturdy roof rack for carrying outdoor gear.',
    price: 129.99,
  },
  {
    brand: 'Toyota',
    model: 'Corolla',
    year: '2022',
    name: 'All-Season Floor Mats',
    description: 'Durable floor mats to keep your car clean.',
    price: 49.99,
  },
  {
    brand: 'Ford',
    model: 'Escape',
    year: '2021',
    name: 'Car Seat Organizer',
    description: 'Convenient organizer for car essentials.',
    price: 19.99,
  },
  {
    brand: 'Toyota',
    model: 'Camry',
    year: '2020',
    name: 'Bluetooth Car Kit',
    description: 'Hands-free communication and music streaming.',
    price: 69.99,
  },
  {
    brand: 'Renault',
    model: 'Kangoo',
    year: '2022',
    name: 'Wireless Phone Charger',
    description: 'Qi-enabled charger for wirelessly charging your phone.',
    price: 39.99,
  },
  {
    brand: 'Toyota',
    model: 'RAV4',
    year: '2020',
    name: 'Cabin Air Filter',
    description: 'High-quality air filter for improved cabin air quality.',
    price: 15.99,
  },
  {
    brand: 'Ford',
    model: 'Fiesta',
    year: '2021',
    name: 'Car Wax Kit',
    description: "Complete kit for polishing and protecting your car's paint.",
    price: 34.99,
  },
  {
    brand: 'Renault',
    model: 'Megane',
    year: '2022',
    name: 'Car Emergency Kit',
    description: 'Essential tools and supplies for roadside emergencies.',
    price: 45.99,
  },
  {
    brand: 'Toyota',
    model: 'Prius',
    year: '2021',
    name: 'GPS Navigation System',
    description: 'High-precision navigation with real-time traffic updates.',
    price: 199.99,
  },
  {
    brand: 'Ford',
    model: 'Mustang',
    year: '2022',
    name: 'Car Cover Lock',
    description: 'Secure your car cover from wind and theft.',
    price: 12.99,
  },
  {
    brand: 'Renault',
    model: 'Talisman',
    year: '2020',
    name: 'Carpeted Trunk Mat',
    description: 'Protect the trunk area from spills and dirt.',
    price: 29.99,
  },
  {
    brand: 'Toyota',
    model: 'Highlander',
    year: '2021',
    name: 'Car Jump Starter',
    description: 'Jump start your car without the need for another vehicle.',
    price: 79.99,
  },
  {
    brand: 'Ford',
    model: 'Explorer',
    year: '2022',
    name: 'Windshield Sun Shade',
    description: 'Reflective shade to keep your car cooler in hot weather.',
    price: 14.99,
  },
  {
    brand: 'Renault',
    model: 'Captur',
    year: '2020',
    name: 'Seat Cushion Set',
    description: 'Comfortable cushioning for long drives.',
    price: 24.99,
  },
];

export default products;
